# Generated by Django 3.2.13 on 2022-08-08 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('phno', models.CharField(max_length=60)),
                ('adharno', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=60)),
                ('date1', models.CharField(max_length=60)),
                ('Time1', models.CharField(max_length=60)),
                ('des', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MCA.register')),
            ],
        ),
    ]
