# Generated by Django 3.2.13 on 2022-08-11 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MCA', '0002_auto_20220811_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='issue1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept', models.CharField(max_length=60)),
                ('photo', models.CharField(max_length=60)),
                ('date1', models.CharField(max_length=60)),
                ('Time1', models.CharField(max_length=60)),
                ('des', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MCA.register1')),
            ],
        ),
    ]
