# Generated by Django 3.2.13 on 2022-08-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCA', '0003_issue1'),
    ]

    operations = [
        migrations.CreateModel(
            name='empreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('uname', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('rpassword', models.CharField(max_length=60)),
                ('dob', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=60)),
                ('phno', models.CharField(max_length=60)),
            ],
        ),
    ]
