# Generated by Django 3.2.3 on 2023-01-30 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MCA', '0006_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='report1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar', models.CharField(max_length=60)),
                ('molass', models.CharField(max_length=60)),
                ('filt', models.CharField(max_length=60)),
                ('baga', models.CharField(max_length=60)),
                ('straw', models.CharField(max_length=60)),
                ('tops', models.CharField(max_length=60)),
                ('total', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MCA.register1')),
            ],
        ),
    ]
