# Generated by Django 3.2.17 on 2023-02-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCA', '0008_report1_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='report1',
            name='ed',
            field=models.CharField(default=0, max_length=60),
        ),
        migrations.AddField(
            model_name='report1',
            name='tton',
            field=models.CharField(default=0, max_length=60),
        ),
    ]
